### ISSUE TITLE
Sculk Blocks todo 

### ISSUE THREAD

**Issue by BluePhoenixLOL** [Soro335/WilderWild#2]
- [x] Sculk Jaw should generate in ground
- [x] Sculk Jaw should be more common
- [x] Sculk Echoer generates on sculk, always has at least one Osseous Sculk hidden below it
- [x] Sculk Echoer should still activate when waterlogged
- [x] Sculk Echoer should also detect vibrations from non-player entities when receiving from sculk sensor
- [x] Sculk Echoer should not emit redstone
- [x] Sculk Echoer should not emit light 
- [x] Osseous Sculk generating in clusters of pillars from the ground and ceiling, the clusters have lots of echoers, especially on top the pillars, and even more on the smaller pillars 
![image](https://user-images.githubusercontent.com/80720298/164056803-4f82ce8c-bd5b-4dd9-bd21-3b39427850a6.png)

- [x] sculk veins don't cover sculk jaws
- [x] replace a most of the sculk veins on osseous pillars with full sculk blocks (especially at the base)
- [x] Hanging Tendril animation shouldn't play while paused

**Comment by AViewFromTheTop** [comment]
@MerpisMe @BluePhoenixLOL should there be a small chance for a Catalyst to generate on top of the pillars as well? I feel like it'd solve a huge problem with renewability and just like cool in general, while keeping the renewability mechanics a bit obscure.

**Comment by BluePhoenixLOL** [comment]
> @MerpisMe @BluePhoenixLOL should there be a small chance for a Catalyst to generate on top of the pillars as well? I feel like it'd solve a huge problem with renewability and just look cool in general, while keeping the renewability mechanics a bit obscure.

idk

**Comment by MerpisMe** [comment]
> @MerpisMe @BluePhoenixLOL should there be a small chance for a Catalyst to generate on top of the pillars as well? I feel like it'd solve a huge problem with renewability and just look cool in general, while keeping the renewability mechanics a bit obscure.

sure, though it would probably look better if we have sculk veins on the block just below the catalyst so it's less of a sudden shift

**Comment by MerpisMe** [comment]
@AViewFromTheTop we actually need to make osseous sculk pillars use features instead of noise, since they generate inside of structures and it oftentimes can ruin a structure. also, they can generate on top of one another.

**Comment by AViewFromTheTop** [comment]
> * [ ]  Hanging Tendril animation shouldn't play while paused

thats a minecraft bug

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop we actually need to make osseous sculk pillars use features (or structures) instead of noise, since they generate inside of structures (ancient cities) and it oftentimes can ruin them. also, they can generate on top of one another.

oh god why

**Comment by MerpisMe** [comment]
> > @AViewFromTheTop we actually need to make osseous sculk pillars use features (or structures) instead of noise, since they generate inside of structures (ancient cities) and it oftentimes can ruin them. also, they can generate on top of one another.
> 
> oh god why

im sorry that minecraft's generation methods suck

**Comment by AViewFromTheTop** [comment]
@MerpisMe making them a feature wouldn't TRULY solve the problem (they can still grow and obstruct stuff sometimes,) but I have a better solution.
