### ISSUE TITLE
New To-Do list for the first release

### ISSUE THREAD

**Issue by Soro335** [Soro335/WilderWild#29]
- [ ] Remove flower forest trees(Help!!! idk how make this)
- [ ] Add new flower forest trees feature
- [ ] Add colormap for flowered lilypad 
- [ ] Add carnation SUSpisious stew 
- [ ] Test a server with mod
- [ ] Rename the mod
- [ ] Other bug fixes

**Comment by AViewFromTheTop** [comment]
Why not just call it Wilder Wild Update

**Comment by AViewFromTheTop** [comment]
Testing on a server rn

**Comment by MerpisMe** [comment]
soro why
can we not rush to release this mod
slow the fuck down please .-.

**Comment by Soro335** [comment]
> soro why can we not rush to release this mod slow the fuck down please .-.

We're not rush, it's just a to-do list

**Comment by AViewFromTheTop** [comment]
apparently mojang screwed up the chat and you can't even send messages on servers, nice.

either way, mod seems to be running just fine
![2022-05-02_19 40 29](https://user-images.githubusercontent.com/87103914/166343481-3e44e5a4-522b-4cc6-bc13-c63ae11d2538.png)
![2022-05-02_19 41 42](https://user-images.githubusercontent.com/87103914/166343491-74b4cda5-70f3-40a5-811f-53bb978d1feb.png)

**Comment by Soro335** [comment]
> apparently mojang screwed up the chat and you can't even send messages on servers, nice.
> 
> either way, mod seems to be running just fine ![2022-05-02_19 40 29](https://user-images.githubusercontent.com/87103914/166343481-3e44e5a4-522b-4cc6-bc13-c63ae11d2538.png) ![2022-05-02_19 41 42](https://user-images.githubusercontent.com/87103914/166343491-74b4cda5-70f3-40a5-811f-53bb978d1feb.png)

Tps is fine too?

**Comment by AViewFromTheTop** [comment]
> Tps is fine too?

you can't check server tps, but it was perfectly fine in singleplayer

**Comment by AViewFromTheTop** [comment]
Issue found:

03.05 00:15:41 [Server] Netty Epoll Server IO #2/ERROR Error receiving packet 90
03.05 00:15:41 [Server] INFO java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@266d7456' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

something about sounds..? Context: Deep Dark.

**Comment by AViewFromTheTop** [comment]
@MerpisMe Sculk Echoers kick players off of servers when they try to play sounds

**Comment by AViewFromTheTop** [comment]
New server-only issue with Ancient Horn:
03.05 01:00:46 [Server] INFO at net.frozenblock.wilderwild.entity.AncientHornProjectileEntity.method_18002(AncientHornProjectileEntity.java:272)

**Comment by AxolotlMC12** [comment]
Archeology??

**Comment by AViewFromTheTop** [comment]
> Archeology??

?

**Comment by Soro335** [comment]
> > Archeology??
> 
> ?

This is not a developer, we do not know how she found the github page if we did not publish links anywhere

**Comment by AViewFromTheTop** [comment]
> This is not a developer, we do not know how she found the github page if we did not publish links anywhere

I know, I'm just confused where they got the idea of us adding Archeology from

**Comment by AViewFromTheTop** [comment]
@Soro335 BTW, I feel like the big Mushrooms are quite out-of-place in the regular forests. Is there any way to make them less common?

**Comment by AViewFromTheTop** [comment]
> Yes, i change that

dangit i forgot to pull your commits

**Comment by MerpisMe** [comment]
@AxolotlMC12 we appreciate your support for the mod, but if possible, could you refrain from commenting on the Github repository, and instead do it on Discord? it helps us all out because we get notifications for every new message and it is misleading when a notification comes from someone other than our dev team. thanks :)

**Comment by AViewFromTheTop** [comment]
> @AxolotlMC12 we appreciate your support for the mod, but if possible, could you refrain from commenting on the Github repository, and instead do it on Discord? it helps us all out because we get notifications for every new message and it is misleading when a notification comes from someone other than our dev team. thanks :)

I don't get notifs for anything

**Comment by MerpisMe** [comment]
> > @AxolotlMC12 we appreciate your support for the mod, but if possible, could you refrain from commenting on the Github repository, and instead do it on Discord? it helps us all out because we get notifications for every new message and it is misleading when a notification comes from someone other than our dev team. thanks :)
> 
> I don't get notifs for anything

1) shhhuut it you're not helping me prove my point
2) excuse me what, how do you know whenever we need you lol

**Comment by BluePhoenixLOL** [comment]
> > it helps us all out because we get notifications for every new message and it is misleading when a notification comes from someone other than our dev team. thanks :)
> 
> I don't get notifs for anything

![image](https://user-images.githubusercontent.com/80720298/166503190-e5fb0375-3bb8-4c85-b49e-7f761236a0a1.png)

**Comment by BluePhoenixLOL** [comment]
we do tho

**Comment by AViewFromTheTop** [comment]
> 2. excuse me what, how do you know whenever we need you lol

i just check back often

**Comment by Soro335** [comment]
@AViewFromTheTop 
![image](https://user-images.githubusercontent.com/82042293/166707345-82f1c1bc-202b-4a67-be11-3c9b6958789a.png)
i found thin in OverworldBiomeCreator. its possible to moddified through mixin?

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop ![image](https://user-images.githubusercontent.com/82042293/166707345-82f1c1bc-202b-4a67-be11-3c9b6958789a.png) i found this in OverworldBiomeCreator. its possible to moddified through mixin?

It's public static, so it may not be able to. Give it a shot, though.

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop should i add this?

Looks fine, but I think the trees with roots should be significantly less common. Cypress trees would help give the generic swamp more character.

**Comment by AViewFromTheTop** [comment]
> > Cypress trees
> 
> Yes.

I'm unfortunate to live next to a Cypress Forest/Swamp, I want to freaking murder the frogs every spring and summer because they never shut the frick up

**Comment by BluePhoenixLOL** [comment]
cypress what??

**Comment by AViewFromTheTop** [comment]
> i live IN a swamp my dude (or, rather, i will until next month when i'm instead moving to a desert :) ) it's horrible here

stop copying shrek i will call his lawyer

**Comment by AViewFromTheTop** [comment]
@MerpisMe I found the Shrek patent and you are not allowed to copy Shrek by living in a swamp: https://patents.google.com/patent/US20210093709A1/en

**Comment by MerpisMe** [comment]
> > i live IN a swamp my dude (or, rather, i will until next month when i'm instead moving to a desert :) ) it's horrible here
> 
> hahahhaahhaahhaahah shrek

it's always humid here, there are so many mosquitos, the roaches here are MASSIVE, the air quality is always at high risk, and it floods here whenever it even so much as sprinkles rain

**Comment by MerpisMe** [comment]
> WHAT CYPRESS

A FUCKKING TREEE

**Comment by AViewFromTheTop** [comment]
> WHAT CYPRESS

go outside

**Comment by BluePhoenixLOL** [comment]
> > WHAT CYPRESS
> 
> A FUCKKING TREEE

IK WDYM

**Comment by BluePhoenixLOL** [comment]
> > WHAT CYPRESS
> 
> go outside

I KNOW WHAT A CYPRESS TREE IS

**Comment by AViewFromTheTop** [comment]
> I KNOW WHAT A CYPRESS TREE IS

then why did you ask

**Comment by BluePhoenixLOL** [comment]
> > I KNOW WHAT A CYPRESS TREE IS
> 
> then why did you ask

are we adding cyypress?

**Comment by MerpisMe** [comment]
we're saying that we _could_ add cypress trees

also please for the love of god send single messages, it spams my phone with buzzes whenever you send a bunch of messages

**Comment by BluePhoenixLOL** [comment]
> we're saying that we _could_ add cypress trees
> 
> also please for the love of god send single messages, it spams my phone with buzzes whenever you send a bunch of messages

sorry, i try not to aaaa

**Comment by AViewFromTheTop** [comment]
@MerpisMe I found the Shrek patent and you are not allowed to copy Shrek by living in a swamp: https://patents.google.com/patent/US20210093709A1/en

**Comment by MerpisMe** [comment]
> > are we adding cyypress?
> 
> if you and soro agree, then i guess

well, i think we should slow down just a tad before we think about that. let's focus on other stuff before we add a whole new wood set. it's on the ideas board for now though

**Comment by AViewFromTheTop** [comment]
> well, i think we should slow down just a tad before we think about that. let's focus on other stuff before we add a whole new wood set. it's on the ideas board for now though

what other stuff exactly

**Comment by AViewFromTheTop** [comment]
![image](https://user-images.githubusercontent.com/87103914/166742016-6f0cea28-b03a-400d-8667-7c4938b77e00.png)

**Comment by Soro335** [comment]
![2022-05-04_20 09 29](https://user-images.githubusercontent.com/82042293/166742012-68694583-6d9a-41c6-a377-f9fc2d979119.png)
I added

**Comment by BluePhoenixLOL** [comment]
is someone going to make a curseforge page?

**Comment by BluePhoenixLOL** [comment]
just set it to experimental and stuff because we arent releasing it yet

**Comment by Soro335** [comment]
we need logo first

**Comment by MerpisMe** [comment]
shut shut shut shut shut shut shut shut

i will make the logo whenever i'm not being bombarded by twenty five thousand different things as the same time
why do we need to make the curseforge page we're not close to releasing the mod

**Comment by AViewFromTheTop** [comment]
> i will make the logo whenever i'm not being bombarded by twenty five thousand different things as the same time why do we need to make the curseforge page we're not close to releasing the mod

So people can't take the name, it's a proof of concept
Also the logo can literally be taken from TWM, you can change the logo once it's ready for release

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop look what i found, do u know how this works?

that's what we're already using to add trees, flowers, etc.

**Comment by Soro335** [comment]
> > @AViewFromTheTop look what i found, do u know how this works?
> 
> that's what we're already using to add trees, flowers, etc.

but it says here that you can remove features, but how?

**Comment by Soro335** [comment]
OMG
![image](https://user-images.githubusercontent.com/82042293/166748386-ba6b0d88-918f-4d65-9ad4-566aa59a3027.png)

**Comment by AViewFromTheTop** [comment]
> OMG ![image](https://user-images.githubusercontent.com/82042293/166748386-ba6b0d88-918f-4d65-9ad4-566aa59a3027.png)

ARE YOU KIDDING ME THIS WAS A THING ALL ALONG DOES IT WORK

**Comment by AViewFromTheTop** [comment]
Flower Forest Doesn't Have Trees Anymore

**Comment by Soro335** [comment]
@AViewFromTheTop do u know how fix this?
![2022-05-09_15 33 52](https://user-images.githubusercontent.com/82042293/167410799-ea89e1cb-8388-432b-b4b9-6da679d9a57f.png)

**Comment by AViewFromTheTop** [comment]
> it's waterlogged not properly

I'll look into it.

**Comment by Soro335** [comment]
@AViewFromTheTop

https://user-images.githubusercontent.com/82042293/167445421-a41a7634-a2d7-4a74-aea2-9b796b726344.mp4
